name: compile-typst 
run-name: ${{ github.actor }}-compile-typst
on: 
  push: 
    branches: 
      - master
jobs: 
  compile-typst:  
    runs-on: ubuntu-latest 
    steps: 
      - name: git-checkout 
        uses: actions/checkout@v4
      - name: install-typst
        uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ
      - name: compile-typst
        run: typst compile main.typ new-main.pdf
      - name: git-push 
        run: | 
          git config --global user.name "Github-Actions"
          git config --global user.email "github-actions@github.com"
          git add new-main.pdf
          git commit -m "comipled typst"
          git push 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

